name: devel
channels:
  - conda-forge
  - conda-forge/label/testing
  - anaconda
dependencies:
  - numpy>=1.15
  - numba>=0.56
  - pyside6
  - qtpy
  - sphinx
  - pytest
  - pytest-xvfb
  - sphinx_rtd_theme
  - requests
  - python-dateutil
  - pyinstaller
  - setuptools
  - certifi
  - pip
  - pip:
    - sphinx-prompt
    - pydocstyle
